version: '3.7'

services:
  api:
    build: api
    container_name: test_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./api:/api

  reddis:
    image: redis:5
    ports:
      - 6379:6379
