version: '3.7'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - 5432:5432

  api:
    build: api
    container_name: test_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: qwe
      DATABASE_PASSWORD: qwe
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
        - db
    volumes:
      - ./api:/api

  reddis:
    image: redis:5
    container_name: reddis
    ports:
      - 6379:6379

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
